export interface RgbEffect {
  id: number;
  name: string;
}

/// RGB Matrix effect list matching QMK firmware config.h enables.
/// IDs correspond to the QMK `rgb_matrix_mode()` enum values.
export const RGB_EFFECTS: RgbEffect[] = [
  { id: 0, name: "Off" },
  { id: 1, name: "Solid Color" },
  { id: 2, name: "Alphas Mods" },
  { id: 3, name: "Gradient Up/Down" },
  { id: 4, name: "Gradient Left/Right" },
  { id: 5, name: "Breathing" },
  { id: 6, name: "Band Sat" },
  { id: 7, name: "Band Val" },
  { id: 8, name: "Band Pinwheel Sat" },
  { id: 9, name: "Band Pinwheel Val" },
  { id: 10, name: "Band Spiral Sat" },
  { id: 11, name: "Band Spiral Val" },
  { id: 12, name: "Cycle All" },
  { id: 13, name: "Cycle Left/Right" },
  { id: 14, name: "Cycle Up/Down" },
  { id: 15, name: "Rainbow Moving Chevron" },
  { id: 16, name: "Cycle Out/In" },
  { id: 17, name: "Cycle Out/In Dual" },
  { id: 18, name: "Cycle Pinwheel" },
  { id: 19, name: "Cycle Spiral" },
  { id: 20, name: "Dual Beacon" },
  { id: 21, name: "Rainbow Beacon" },
  { id: 22, name: "Rainbow Pinwheels" },
  { id: 23, name: "Flower Blooming" },
  { id: 24, name: "Raindrops" },
  { id: 25, name: "Jellybean Raindrops" },
  { id: 26, name: "Hue Breathing" },
  { id: 27, name: "Hue Pendulum" },
  { id: 28, name: "Hue Wave" },
  { id: 29, name: "Pixel Fractal" },
  { id: 30, name: "Pixel Flow" },
  { id: 31, name: "Pixel Rain" },
  { id: 32, name: "Typing Heatmap" },
  { id: 33, name: "Digital Rain" },
  { id: 34, name: "Solid Reactive Simple" },
  { id: 35, name: "Solid Reactive" },
  { id: 36, name: "Solid Reactive Wide" },
  { id: 37, name: "Solid Reactive Multiwide" },
  { id: 38, name: "Solid Reactive Cross" },
  { id: 39, name: "Solid Reactive Multicross" },
  { id: 40, name: "Solid Reactive Nexus" },
  { id: 41, name: "Solid Reactive Multinexus" },
  { id: 42, name: "Splash" },
  { id: 43, name: "Multisplash" },
  { id: 44, name: "Solid Splash" },
  { id: 45, name: "Solid Multisplash" },
];
