export interface RgbEffect {
  id: number;
  name: string;
  desc: string;
}

/// RGB Matrix effect list matching QMK firmware config.h enables.
/// IDs correspond to the QMK `rgb_matrix_mode()` enum values.
export const RGB_EFFECTS: RgbEffect[] = [
  { id: 0, name: "Off", desc: "LEDs off" },
  { id: 1, name: "Solid", desc: "Static single color" },
  { id: 2, name: "Alphas Mods", desc: "Alternate key colors" },
  { id: 3, name: "Gradient V", desc: "Vertical gradient" },
  { id: 4, name: "Gradient H", desc: "Horizontal gradient" },
  { id: 5, name: "Breathing", desc: "Pulse in and out" },
  { id: 6, name: "Band Sat", desc: "Moving saturation band" },
  { id: 7, name: "Band Val", desc: "Moving brightness band" },
  { id: 8, name: "Pinwheel Sat", desc: "Rotating sat pinwheel" },
  { id: 9, name: "Pinwheel Val", desc: "Rotating val pinwheel" },
  { id: 10, name: "Spiral Sat", desc: "Spiral saturation wave" },
  { id: 11, name: "Spiral Val", desc: "Spiral brightness wave" },
  { id: 12, name: "Cycle All", desc: "All keys cycle hue" },
  { id: 13, name: "Cycle L/R", desc: "Hue sweeps left to right" },
  { id: 14, name: "Cycle U/D", desc: "Hue sweeps top to bottom" },
  { id: 15, name: "Rainbow Chevron", desc: "Moving rainbow chevron" },
  { id: 16, name: "Cycle Out/In", desc: "Hue radiates outward" },
  { id: 17, name: "Cycle Dual", desc: "Dual hue radiation" },
  { id: 18, name: "Cycle Pinwheel", desc: "Hue rotating pinwheel" },
  { id: 19, name: "Cycle Spiral", desc: "Hue spiral motion" },
  { id: 20, name: "Dual Beacon", desc: "Two rotating beacons" },
  { id: 21, name: "Rainbow Beacon", desc: "Rotating rainbow sweep" },
  { id: 22, name: "Rainbow Pinwheels", desc: "Multiple rainbow wheels" },
  { id: 23, name: "Flower Bloom", desc: "Blooming flower pattern" },
  { id: 24, name: "Raindrops", desc: "Random color raindrops" },
  { id: 25, name: "Jellybean", desc: "Colorful jellybean drops" },
  { id: 26, name: "Hue Breathing", desc: "Breathing with hue shift" },
  { id: 27, name: "Hue Pendulum", desc: "Hue swings back & forth" },
  { id: 28, name: "Hue Wave", desc: "Smooth traveling hue wave" },
  { id: 29, name: "Pixel Fractal", desc: "Fractal pixel patterns" },
  { id: 30, name: "Pixel Flow", desc: "Flowing pixel streams" },
  { id: 31, name: "Pixel Rain", desc: "Raining pixel drops" },
  { id: 32, name: "Typing Heatmap", desc: "Heat map on keypress" },
  { id: 33, name: "Digital Rain", desc: "Matrix-style rain" },
  { id: 34, name: "Reactive", desc: "Flash on keypress" },
  { id: 35, name: "Reactive Solid", desc: "Solid flash on press" },
  { id: 36, name: "Reactive Wide", desc: "Wide flash on press" },
  { id: 37, name: "Reactive Multi", desc: "Multi-key wide flash" },
  { id: 38, name: "Reactive Cross", desc: "Cross flash on press" },
  { id: 39, name: "Reactive X", desc: "Multi cross flash" },
  { id: 40, name: "Reactive Nexus", desc: "Nexus ripple on press" },
  { id: 41, name: "Reactive Multi N", desc: "Multi nexus ripple" },
  { id: 42, name: "Splash", desc: "Color splash on press" },
  { id: 43, name: "Multisplash", desc: "Multiple splashes" },
  { id: 44, name: "Solid Splash", desc: "Solid color splash" },
  { id: 45, name: "Solid Multi", desc: "Solid multi splash" },
];
